/* Generated by Yosys 0.20+42 (git sha1 1c36f4cc2, clang  -fPIC -Os) */

module UART_TX(i_Clock, i_TX_DV, i_TX_Byte, o_TX_Active, o_TX_Serial, o_TX_Done);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire [2:0] _071_;
  input i_Clock;
  wire i_Clock;
  input [7:0] i_TX_Byte;
  wire [7:0] i_TX_Byte;
  input i_TX_DV;
  wire i_TX_DV;
  output o_TX_Active;
  wire o_TX_Active;
  output o_TX_Done;
  wire o_TX_Done;
  output o_TX_Serial;
  wire o_TX_Serial;
  wire [2:0] r_Bit_Index;
  wire [7:0] r_Clock_Count;
  wire [2:0] r_SM_Main;
  wire r_TX_Active;
  wire [7:0] r_TX_Data;
  wire r_TX_Done;
  sky130_fd_sc_hd__nor2_1 _072_ (
    .A(_044_),
    .B(_055_),
    .Y(_071_[2])
  );
  sky130_fd_sc_hd__o21ai_0 _073_ (
    .A1(_044_),
    .A2(_055_),
    .B1(r_TX_Active),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _074_ (
    .A(_053_),
    .B(_056_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _075_ (
    .A(r_SM_Main[2]),
    .B(r_Clock_Count[0]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a311oi_1 _076_ (
    .A1(r_Clock_Count[6]),
    .A2(r_Clock_Count[7]),
    .A3(_041_),
    .B1(_050_),
    .C1(r_SM_Main[2]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__or3_1 _077_ (
    .A(r_SM_Main[2]),
    .B(_043_),
    .C(_050_),
    .X(_059_)
  );
  sky130_fd_sc_hd__o21ai_0 _078_ (
    .A1(r_Clock_Count[0]),
    .A2(_059_),
    .B1(_057_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _079_ (
    .A(r_Clock_Count[0]),
    .B(r_Clock_Count[1]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _080_ (
    .A(r_SM_Main[2]),
    .B(r_Clock_Count[1]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _081_ (
    .A(r_Clock_Count[0]),
    .B(r_Clock_Count[1]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _082_ (
    .A(_058_),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _083_ (
    .A1(_061_),
    .A2(_063_),
    .B1(_060_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _084_ (
    .A(r_SM_Main[2]),
    .B(r_Clock_Count[2]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xor2_1 _085_ (
    .A(r_Clock_Count[2]),
    .B(_062_),
    .X(_065_)
  );
  sky130_fd_sc_hd__o21ai_0 _086_ (
    .A1(_059_),
    .A2(_065_),
    .B1(_064_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a31oi_1 _087_ (
    .A1(r_Clock_Count[0]),
    .A2(r_Clock_Count[1]),
    .A3(r_Clock_Count[2]),
    .B1(r_Clock_Count[3]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _088_ (
    .A(r_Clock_Count[3]),
    .B(r_SM_Main[2]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__and4_1 _089_ (
    .A(r_Clock_Count[3]),
    .B(r_Clock_Count[0]),
    .C(r_Clock_Count[1]),
    .D(r_Clock_Count[2]),
    .X(_068_)
  );
  sky130_fd_sc_hd__o31ai_1 _090_ (
    .A1(_059_),
    .A2(_066_),
    .A3(_068_),
    .B1(_067_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _091_ (
    .A(r_Clock_Count[4]),
    .B(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _092_ (
    .A(r_Clock_Count[4]),
    .B(r_SM_Main[2]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _093_ (
    .A(r_Clock_Count[4]),
    .B(_068_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(_058_),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__o21ai_0 _095_ (
    .A1(_069_),
    .A2(_023_),
    .B1(_070_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _096_ (
    .A(r_Clock_Count[5]),
    .B(r_SM_Main[2]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xor2_1 _097_ (
    .A(r_Clock_Count[5]),
    .B(_022_),
    .X(_025_)
  );
  sky130_fd_sc_hd__o21ai_0 _098_ (
    .A1(_059_),
    .A2(_025_),
    .B1(_024_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand4_1 _099_ (
    .A(r_Clock_Count[6]),
    .B(r_Clock_Count[5]),
    .C(r_Clock_Count[4]),
    .D(_068_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _100_ (
    .A1(_058_),
    .A2(_026_),
    .B1(r_SM_Main[2]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a41oi_1 _101_ (
    .A1(r_Clock_Count[5]),
    .A2(r_Clock_Count[4]),
    .A3(_058_),
    .A4(_068_),
    .B1(r_Clock_Count[6]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _102_ (
    .A(_027_),
    .B(_028_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o22ai_1 _103_ (
    .A1(_059_),
    .A2(_026_),
    .B1(_027_),
    .B2(_039_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o31ai_1 _104_ (
    .A1(_040_),
    .A2(_042_),
    .A3(_045_),
    .B1(_052_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(r_Bit_Index[0]),
    .B(_046_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _106_ (
    .A1(r_Bit_Index[0]),
    .A2(_029_),
    .B1(_030_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _107_ (
    .A1(r_Bit_Index[0]),
    .A2(_029_),
    .B1(r_Bit_Index[1]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a311oi_1 _108_ (
    .A1(r_Bit_Index[0]),
    .A2(r_Bit_Index[1]),
    .A3(_046_),
    .B1(_051_),
    .C1(_031_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a31o_1 _109_ (
    .A1(r_Bit_Index[0]),
    .A2(r_Bit_Index[1]),
    .A3(_029_),
    .B1(r_Bit_Index[2]),
    .X(_032_)
  );
  sky130_fd_sc_hd__and3_1 _110_ (
    .A(_047_),
    .B(_052_),
    .C(_032_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux4_2 _111_ (
    .A0(r_TX_Data[2]),
    .A1(r_TX_Data[3]),
    .A2(r_TX_Data[6]),
    .A3(r_TX_Data[7]),
    .S0(r_Bit_Index[0]),
    .S1(r_Bit_Index[2]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _112_ (
    .A(r_Bit_Index[1]),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__mux4_2 _113_ (
    .A0(r_TX_Data[0]),
    .A1(r_TX_Data[1]),
    .A2(r_TX_Data[4]),
    .A3(r_TX_Data[5]),
    .S0(r_Bit_Index[0]),
    .S1(r_Bit_Index[2]),
    .X(_035_)
  );
  sky130_fd_sc_hd__nand2b_1 _114_ (
    .A_N(r_Bit_Index[1]),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a311o_1 _115_ (
    .A1(r_SM_Main[1]),
    .A2(_034_),
    .A3(_036_),
    .B1(r_SM_Main[0]),
    .C1(r_SM_Main[2]),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(r_SM_Main[2]),
    .B(o_TX_Serial),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand3_1 _117_ (
    .A(_055_),
    .B(_037_),
    .C(_038_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _118_ (
    .A0(i_TX_Byte[0]),
    .A1(r_TX_Data[0]),
    .S(_053_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _119_ (
    .A0(i_TX_Byte[1]),
    .A1(r_TX_Data[1]),
    .S(_053_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _120_ (
    .A0(i_TX_Byte[2]),
    .A1(r_TX_Data[2]),
    .S(_053_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _121_ (
    .A0(i_TX_Byte[3]),
    .A1(r_TX_Data[3]),
    .S(_053_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _122_ (
    .A0(i_TX_Byte[4]),
    .A1(r_TX_Data[4]),
    .S(_053_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _123_ (
    .A0(i_TX_Byte[5]),
    .A1(r_TX_Data[5]),
    .S(_053_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _124_ (
    .A0(i_TX_Byte[6]),
    .A1(r_TX_Data[6]),
    .S(_053_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _125_ (
    .A0(i_TX_Byte[7]),
    .A1(r_TX_Data[7]),
    .S(_053_),
    .X(_020_)
  );
  sky130_fd_sc_hd__o31a_1 _126_ (
    .A1(r_TX_Done),
    .A2(_050_),
    .A3(_071_[2]),
    .B1(_052_),
    .X(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _127_ (
    .A(r_Clock_Count[7]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a21oi_1 _128_ (
    .A1(r_Clock_Count[4]),
    .A2(r_Clock_Count[3]),
    .B1(r_Clock_Count[5]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21o_1 _129_ (
    .A1(r_Clock_Count[4]),
    .A2(r_Clock_Count[3]),
    .B1(r_Clock_Count[5]),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _130_ (
    .A(r_Clock_Count[6]),
    .B(r_Clock_Count[7]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _131_ (
    .A(_040_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand3_1 _132_ (
    .A(r_Clock_Count[6]),
    .B(r_Clock_Count[7]),
    .C(_041_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__or3b_1 _133_ (
    .A(r_SM_Main[2]),
    .B(r_SM_Main[0]),
    .C_N(r_SM_Main[1]),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _134_ (
    .A(_040_),
    .B(_042_),
    .C(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand4_1 _135_ (
    .A(r_Bit_Index[0]),
    .B(r_Bit_Index[2]),
    .C(r_Bit_Index[1]),
    .D(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2b_1 _136_ (
    .A(r_SM_Main[2]),
    .B_N(r_SM_Main[0]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _137_ (
    .A(_044_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _138_ (
    .A(r_SM_Main[0]),
    .B(r_SM_Main[1]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor3_1 _139_ (
    .A(r_SM_Main[2]),
    .B(r_SM_Main[0]),
    .C(r_SM_Main[1]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__or3_1 _140_ (
    .A(r_SM_Main[2]),
    .B(r_SM_Main[0]),
    .C(r_SM_Main[1]),
    .X(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _141_ (
    .A(i_TX_DV),
    .B(_051_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand3_1 _142_ (
    .A(_047_),
    .B(_049_),
    .C(_053_),
    .Y(_071_[0])
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(_043_),
    .B(_048_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _144_ (
    .A(r_SM_Main[1]),
    .B(_048_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o221ai_1 _145_ (
    .A1(r_SM_Main[1]),
    .A2(_054_),
    .B1(_055_),
    .B2(_043_),
    .C1(_045_),
    .Y(_071_[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _146_ (
    .CLK(i_Clock),
    .D(_000_),
    .Q(r_TX_Active)
  );
  sky130_fd_sc_hd__dfxtp_1 _147_ (
    .CLK(i_Clock),
    .D(_001_),
    .Q(r_Clock_Count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _148_ (
    .CLK(i_Clock),
    .D(_002_),
    .Q(r_Clock_Count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _149_ (
    .CLK(i_Clock),
    .D(_003_),
    .Q(r_Clock_Count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _150_ (
    .CLK(i_Clock),
    .D(_004_),
    .Q(r_Clock_Count[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _151_ (
    .CLK(i_Clock),
    .D(_005_),
    .Q(r_Clock_Count[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _152_ (
    .CLK(i_Clock),
    .D(_006_),
    .Q(r_Clock_Count[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _153_ (
    .CLK(i_Clock),
    .D(_007_),
    .Q(r_Clock_Count[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _154_ (
    .CLK(i_Clock),
    .D(_008_),
    .Q(r_Clock_Count[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _155_ (
    .CLK(i_Clock),
    .D(_009_),
    .Q(r_Bit_Index[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _156_ (
    .CLK(i_Clock),
    .D(_010_),
    .Q(r_Bit_Index[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _157_ (
    .CLK(i_Clock),
    .D(_011_),
    .Q(r_Bit_Index[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _158_ (
    .CLK(i_Clock),
    .D(_071_[0]),
    .Q(r_SM_Main[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _159_ (
    .CLK(i_Clock),
    .D(_071_[1]),
    .Q(r_SM_Main[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _160_ (
    .CLK(i_Clock),
    .D(_071_[2]),
    .Q(r_SM_Main[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _161_ (
    .CLK(i_Clock),
    .D(_012_),
    .Q(o_TX_Serial)
  );
  sky130_fd_sc_hd__dfxtp_1 _162_ (
    .CLK(i_Clock),
    .D(_013_),
    .Q(r_TX_Data[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _163_ (
    .CLK(i_Clock),
    .D(_014_),
    .Q(r_TX_Data[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _164_ (
    .CLK(i_Clock),
    .D(_015_),
    .Q(r_TX_Data[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _165_ (
    .CLK(i_Clock),
    .D(_016_),
    .Q(r_TX_Data[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _166_ (
    .CLK(i_Clock),
    .D(_017_),
    .Q(r_TX_Data[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _167_ (
    .CLK(i_Clock),
    .D(_018_),
    .Q(r_TX_Data[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _168_ (
    .CLK(i_Clock),
    .D(_019_),
    .Q(r_TX_Data[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _169_ (
    .CLK(i_Clock),
    .D(_020_),
    .Q(r_TX_Data[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _170_ (
    .CLK(i_Clock),
    .D(_021_),
    .Q(r_TX_Done)
  );
  assign o_TX_Active = r_TX_Active;
  assign o_TX_Done = r_TX_Done;
endmodule
