/* Generated by Yosys 0.20+42 (git sha1 1c36f4cc2, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "iiitb_uarttx.v:14.1-161.10" *)
module UART_TX(i_Clock, i_TX_DV, i_TX_Byte, o_TX_Active, o_TX_Serial, o_TX_Done);
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  wire _000_;
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  wire _089_;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  wire _090_;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  wire _091_;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  wire _092_;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  wire _093_;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  wire _094_;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  wire _095_;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  wire _096_;
  (* src = "iiitb_uarttx.v:18.16-18.23" *)
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  (* src = "iiitb_uarttx.v:21.16-21.27" *)
  wire _147_;
  (* src = "iiitb_uarttx.v:0.0-0.0|iiitb_uarttx.v:44.5-155.12|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _148_;
  (* src = "iiitb_uarttx.v:0.0-0.0|iiitb_uarttx.v:44.5-155.12|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _149_;
  (* src = "iiitb_uarttx.v:0.0-0.0|iiitb_uarttx.v:44.5-155.12|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _150_;
  (* src = "iiitb_uarttx.v:33.13-33.24" *)
  wire _151_;
  (* src = "iiitb_uarttx.v:33.13-33.24" *)
  wire _152_;
  (* src = "iiitb_uarttx.v:33.13-33.24" *)
  wire _153_;
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire _154_;
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire _155_;
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire _156_;
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire _157_;
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire _158_;
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire _159_;
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire _160_;
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire _161_;
  (* src = "iiitb_uarttx.v:31.13-31.22" *)
  wire _162_;
  (* src = "iiitb_uarttx.v:31.13-31.22" *)
  wire _163_;
  (* src = "iiitb_uarttx.v:31.13-31.22" *)
  wire _164_;
  (* src = "iiitb_uarttx.v:36.13-36.24" *)
  wire _165_;
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire _166_;
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire _167_;
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire _168_;
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire _169_;
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire _170_;
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire _171_;
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire _172_;
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire _173_;
  (* src = "iiitb_uarttx.v:35.13-35.22" *)
  wire _174_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_uarttx.v:108.30-108.45|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _175_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_uarttx.v:108.30-108.45|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [2:0] _176_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_uarttx.v:129.30-129.47|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [7:0] _177_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_uarttx.v:129.30-129.47|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_uarttx.v:0.0-0.0|iiitb_uarttx.v:44.5-155.12|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _212_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_uarttx.v:0.0-0.0|iiitb_uarttx.v:44.5-155.12|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  (* unused_bits = "0 1 2 3 4 6 7" *)
  wire [11:0] _213_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_uarttx.v:0.0-0.0|iiitb_uarttx.v:44.5-155.12|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] _214_;
  (* src = "iiitb_uarttx.v:17.16-17.23" *)
  input i_Clock;
  wire i_Clock;
  (* src = "iiitb_uarttx.v:19.16-19.25" *)
  input [7:0] i_TX_Byte;
  wire [7:0] i_TX_Byte;
  (* src = "iiitb_uarttx.v:18.16-18.23" *)
  input i_TX_DV;
  wire i_TX_DV;
  (* src = "iiitb_uarttx.v:20.16-20.27" *)
  output o_TX_Active;
  wire o_TX_Active;
  (* src = "iiitb_uarttx.v:22.16-22.25" *)
  output o_TX_Done;
  wire o_TX_Done;
  (* src = "iiitb_uarttx.v:21.16-21.27" *)
  output o_TX_Serial;
  wire o_TX_Serial;
  (* init = 3'h0 *)
  (* src = "iiitb_uarttx.v:33.13-33.24" *)
  wire [2:0] r_Bit_Index;
  (* init = 8'h00 *)
  (* src = "iiitb_uarttx.v:32.13-32.26" *)
  wire [7:0] r_Clock_Count;
  (* init = 3'h0 *)
  (* src = "iiitb_uarttx.v:31.13-31.22" *)
  wire [2:0] r_SM_Main;
  (* init = 1'h0 *)
  (* src = "iiitb_uarttx.v:36.13-36.24" *)
  wire r_TX_Active;
  (* init = 8'h00 *)
  (* src = "iiitb_uarttx.v:34.13-34.22" *)
  wire [7:0] r_TX_Data;
  (* init = 1'h0 *)
  (* src = "iiitb_uarttx.v:35.13-35.22" *)
  wire r_TX_Done;
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(_120_),
    .B(_131_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _216_ (
    .A1(_120_),
    .A2(_131_),
    .B1(_165_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(_129_),
    .B(_132_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(_164_),
    .B(_154_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a311oi_1 _219_ (
    .A1(_160_),
    .A2(_161_),
    .A3(_117_),
    .B1(_126_),
    .C1(_164_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__or3_1 _220_ (
    .A(_164_),
    .B(_119_),
    .C(_126_),
    .X(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _221_ (
    .A1(_154_),
    .A2(_135_),
    .B1(_133_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_154_),
    .B(_155_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(_164_),
    .B(_155_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_154_),
    .B(_155_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(_134_),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _226_ (
    .A1(_137_),
    .A2(_139_),
    .B1(_136_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(_164_),
    .B(_156_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__xor2_1 _228_ (
    .A(_156_),
    .B(_138_),
    .X(_141_)
  );
  sky130_fd_sc_hd__o21ai_0 _229_ (
    .A1(_135_),
    .A2(_141_),
    .B1(_140_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a31oi_1 _230_ (
    .A1(_154_),
    .A2(_155_),
    .A3(_156_),
    .B1(_157_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(_157_),
    .B(_164_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__and4_1 _232_ (
    .A(_157_),
    .B(_154_),
    .C(_155_),
    .D(_156_),
    .X(_144_)
  );
  sky130_fd_sc_hd__o31ai_1 _233_ (
    .A1(_135_),
    .A2(_142_),
    .A3(_144_),
    .B1(_143_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _234_ (
    .A(_158_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(_158_),
    .B(_164_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_158_),
    .B(_144_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(_134_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o21ai_0 _238_ (
    .A1(_145_),
    .A2(_099_),
    .B1(_146_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_159_),
    .B(_164_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xor2_1 _240_ (
    .A(_159_),
    .B(_098_),
    .X(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _241_ (
    .A1(_135_),
    .A2(_101_),
    .B1(_100_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand4_1 _242_ (
    .A(_160_),
    .B(_159_),
    .C(_158_),
    .D(_144_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _243_ (
    .A1(_134_),
    .A2(_102_),
    .B1(_164_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a41oi_1 _244_ (
    .A1(_159_),
    .A2(_158_),
    .A3(_134_),
    .A4(_144_),
    .B1(_160_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _245_ (
    .A(_103_),
    .B(_104_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o22ai_1 _246_ (
    .A1(_135_),
    .A2(_102_),
    .B1(_103_),
    .B2(_115_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o31ai_1 _247_ (
    .A1(_116_),
    .A2(_118_),
    .A3(_121_),
    .B1(_128_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _248_ (
    .A(_151_),
    .B(_122_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _249_ (
    .A1(_151_),
    .A2(_105_),
    .B1(_106_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a21oi_1 _250_ (
    .A1(_151_),
    .A2(_105_),
    .B1(_152_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a311oi_1 _251_ (
    .A1(_151_),
    .A2(_152_),
    .A3(_122_),
    .B1(_127_),
    .C1(_107_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a31o_1 _252_ (
    .A1(_151_),
    .A2(_152_),
    .A3(_105_),
    .B1(_153_),
    .X(_108_)
  );
  sky130_fd_sc_hd__and3_1 _253_ (
    .A(_123_),
    .B(_128_),
    .C(_108_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux4_2 _254_ (
    .A0(_168_),
    .A1(_169_),
    .A2(_172_),
    .A3(_173_),
    .S0(_151_),
    .S1(_153_),
    .X(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(_152_),
    .B(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__mux4_2 _256_ (
    .A0(_166_),
    .A1(_167_),
    .A2(_170_),
    .A3(_171_),
    .S0(_151_),
    .S1(_153_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nand2b_1 _257_ (
    .A_N(_152_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a311o_1 _258_ (
    .A1(_163_),
    .A2(_110_),
    .A3(_112_),
    .B1(_162_),
    .C1(_164_),
    .X(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(_164_),
    .B(_147_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand3_1 _260_ (
    .A(_131_),
    .B(_113_),
    .C(_114_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__mux2_1 _261_ (
    .A0(_089_),
    .A1(_166_),
    .S(_129_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _262_ (
    .A0(_090_),
    .A1(_167_),
    .S(_129_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_1 _263_ (
    .A0(_091_),
    .A1(_168_),
    .S(_129_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _264_ (
    .A0(_092_),
    .A1(_169_),
    .S(_129_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _265_ (
    .A0(_093_),
    .A1(_170_),
    .S(_129_),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _266_ (
    .A0(_094_),
    .A1(_171_),
    .S(_129_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _267_ (
    .A0(_095_),
    .A1(_172_),
    .S(_129_),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _268_ (
    .A0(_096_),
    .A1(_173_),
    .S(_129_),
    .X(_087_)
  );
  sky130_fd_sc_hd__o31a_1 _269_ (
    .A1(_174_),
    .A2(_126_),
    .A3(_150_),
    .B1(_128_),
    .X(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _270_ (
    .A(_161_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a21oi_1 _271_ (
    .A1(_158_),
    .A2(_157_),
    .B1(_159_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21o_1 _272_ (
    .A1(_158_),
    .A2(_157_),
    .B1(_159_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(_160_),
    .B(_161_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _274_ (
    .A(_116_),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand3_1 _275_ (
    .A(_160_),
    .B(_161_),
    .C(_117_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__or3b_1 _276_ (
    .A(_164_),
    .B(_162_),
    .C_N(_163_),
    .X(_121_)
  );
  sky130_fd_sc_hd__nor3_1 _277_ (
    .A(_116_),
    .B(_118_),
    .C(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand4_1 _278_ (
    .A(_151_),
    .B(_153_),
    .C(_152_),
    .D(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2b_1 _279_ (
    .A(_164_),
    .B_N(_162_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(_120_),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(_162_),
    .B(_163_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor3_1 _282_ (
    .A(_164_),
    .B(_162_),
    .C(_163_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__or3_1 _283_ (
    .A(_164_),
    .B(_162_),
    .C(_163_),
    .X(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _284_ (
    .A(_097_),
    .B(_127_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand3_1 _285_ (
    .A(_123_),
    .B(_125_),
    .C(_129_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _286_ (
    .A(_119_),
    .B(_124_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(_163_),
    .B(_124_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o221ai_1 _288_ (
    .A1(_163_),
    .A2(_130_),
    .B1(_131_),
    .B2(_119_),
    .C1(_121_),
    .Y(_149_)
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _289_ (
    .CLK(i_Clock),
    .D(_179_),
    .Q(r_TX_Active)
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _290_ (
    .CLK(i_Clock),
    .D(_181_),
    .Q(r_Clock_Count[0])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _291_ (
    .CLK(i_Clock),
    .D(_183_),
    .Q(r_Clock_Count[1])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _292_ (
    .CLK(i_Clock),
    .D(_185_),
    .Q(r_Clock_Count[2])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _293_ (
    .CLK(i_Clock),
    .D(_187_),
    .Q(r_Clock_Count[3])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _294_ (
    .CLK(i_Clock),
    .D(_189_),
    .Q(r_Clock_Count[4])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _295_ (
    .CLK(i_Clock),
    .D(_191_),
    .Q(r_Clock_Count[5])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _296_ (
    .CLK(i_Clock),
    .D(_193_),
    .Q(r_Clock_Count[6])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _297_ (
    .CLK(i_Clock),
    .D(_195_),
    .Q(r_Clock_Count[7])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _298_ (
    .CLK(i_Clock),
    .D(_197_),
    .Q(r_Bit_Index[0])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _299_ (
    .CLK(i_Clock),
    .D(_199_),
    .Q(r_Bit_Index[1])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _300_ (
    .CLK(i_Clock),
    .D(_201_),
    .Q(r_Bit_Index[2])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _301_ (
    .CLK(i_Clock),
    .D(_214_[0]),
    .Q(r_SM_Main[0])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _302_ (
    .CLK(i_Clock),
    .D(_214_[1]),
    .Q(r_SM_Main[1])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _303_ (
    .CLK(i_Clock),
    .D(_214_[2]),
    .Q(r_SM_Main[2])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _304_ (
    .CLK(i_Clock),
    .D(_202_),
    .Q(o_TX_Serial)
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _305_ (
    .CLK(i_Clock),
    .D(_203_),
    .Q(r_TX_Data[0])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _306_ (
    .CLK(i_Clock),
    .D(_204_),
    .Q(r_TX_Data[1])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _307_ (
    .CLK(i_Clock),
    .D(_205_),
    .Q(r_TX_Data[2])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _308_ (
    .CLK(i_Clock),
    .D(_206_),
    .Q(r_TX_Data[3])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _309_ (
    .CLK(i_Clock),
    .D(_207_),
    .Q(r_TX_Data[4])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _310_ (
    .CLK(i_Clock),
    .D(_208_),
    .Q(r_TX_Data[5])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _311_ (
    .CLK(i_Clock),
    .D(_209_),
    .Q(r_TX_Data[6])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _312_ (
    .CLK(i_Clock),
    .D(_210_),
    .Q(r_TX_Data[7])
  );
  (* src = "iiitb_uarttx.v:41.3-156.6" *)
  sky130_fd_sc_hd__dfxtp_1 _313_ (
    .CLK(i_Clock),
    .D(_211_),
    .Q(r_TX_Done)
  );
  assign _175_[2:1] = r_Bit_Index[2:1];
  assign _176_[0] = _175_[0];
  assign _177_[7:1] = r_Clock_Count[7:1];
  assign _178_[0] = _177_[0];
  assign { _213_[11:10], _213_[8], _213_[5], _213_[0] } = { 4'h0, _213_[1] };
  assign o_TX_Active = r_TX_Active;
  assign o_TX_Done = r_TX_Done;
  assign _151_ = r_Bit_Index[0];
  assign _160_ = r_Clock_Count[6];
  assign _159_ = r_Clock_Count[5];
  assign _158_ = r_Clock_Count[4];
  assign _157_ = r_Clock_Count[3];
  assign _161_ = r_Clock_Count[7];
  assign _164_ = r_SM_Main[2];
  assign _162_ = r_SM_Main[0];
  assign _163_ = r_SM_Main[1];
  assign _153_ = r_Bit_Index[2];
  assign _152_ = r_Bit_Index[1];
  assign _097_ = i_TX_DV;
  assign _214_[0] = _148_;
  assign _214_[1] = _149_;
  assign _214_[2] = _150_;
  assign _166_ = r_TX_Data[0];
  assign _167_ = r_TX_Data[1];
  assign _168_ = r_TX_Data[2];
  assign _169_ = r_TX_Data[3];
  assign _170_ = r_TX_Data[4];
  assign _171_ = r_TX_Data[5];
  assign _172_ = r_TX_Data[6];
  assign _173_ = r_TX_Data[7];
  assign _154_ = r_Clock_Count[0];
  assign _155_ = r_Clock_Count[1];
  assign _156_ = r_Clock_Count[2];
  assign _165_ = r_TX_Active;
  assign _179_ = _067_;
  assign _181_ = _068_;
  assign _183_ = _069_;
  assign _185_ = _070_;
  assign _187_ = _071_;
  assign _189_ = _072_;
  assign _191_ = _073_;
  assign _193_ = _074_;
  assign _195_ = _075_;
  assign _197_ = _076_;
  assign _199_ = _077_;
  assign _201_ = _078_;
  assign _147_ = o_TX_Serial;
  assign _202_ = _079_;
  assign _089_ = i_TX_Byte[0];
  assign _203_ = _080_;
  assign _090_ = i_TX_Byte[1];
  assign _204_ = _081_;
  assign _091_ = i_TX_Byte[2];
  assign _205_ = _082_;
  assign _092_ = i_TX_Byte[3];
  assign _206_ = _083_;
  assign _093_ = i_TX_Byte[4];
  assign _207_ = _084_;
  assign _094_ = i_TX_Byte[5];
  assign _208_ = _085_;
  assign _095_ = i_TX_Byte[6];
  assign _209_ = _086_;
  assign _096_ = i_TX_Byte[7];
  assign _210_ = _087_;
  assign _174_ = r_TX_Done;
  assign _211_ = _088_;
endmodule
